name: Homebrew
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  homebrew:
    name: "Create homebrew release"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
          cargo build --release --target x86_64-apple-darwin
          cargo build --release --target aarch64-apple-darwin

      - name: Create universal binary
        id: archive
        run: |
          lipo -create -output ./dark-notify target/x86_64-apple-darwin/release/dark-notify target/aarch64-apple-darwin/release/dark-notify
          tar -czvf dark-notify.tar.gz ./dark-notify

          SUM=$(shasum -a 256 dark-notify.tar.gz | awk '{print $1}')
          echo "shasum=$SUM" >> $GITHUB_OUTPUT

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            dark-notify.tar.gz
          fail_on_unmatched_files: true

      - name: Get asset URL
        id: get_url
        run: |
          URL="${{ fromJson(steps.release.outputs.assets)[0].browser_download_url }}"
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Update Homebrew formula
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BREW_TOKEN }}
          VERSION: ${{ github.ref_name }}
        run: |
          brew tap cormacrelf/tap
          brew bump-formula-pr -f --no-browse --no-audit \
            --version="${VERSION#v}" \
            --sha256="${{ steps.archive.outputs.shasum }}" \
            --url="${{ steps.get_url.outputs.url }}" \
            cormacrelf/tap/dark-notify
